### ISSUE TITLE
Remove X11 dependency?

### ISSUE THREAD

**Issue by thomasjm** [codedownio/sandwich#21]
All we need is the ability to get screen resolution and move windows around. Maybe make a small cross-platform lib similar to 

https://github.com/rr-/screeninfo/tree/master/screeninfo/enumerators

**Comment by djanatyn** [comment]
I'm unable to use this package on MacOS 10.13.6 due to the `X11` dependency. The latest linker available to me fails to compile:
```
Linking dist/build/hsc2hs/hsc2hs ...
Undefined symbols for architecture x86_64:
  "___darwin_check_fd_set_overflow", referenced from:
      _awaitEvent in libHSrts.a(Select.o)
ld: symbol(s) not found for architecture x86_64   
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build X11-1.10
```

I think this can be fixed by upgrading MacOS and Xcode. Unfortunately, that's not an option for me right now.

`sandwich-webdriver` provides functionality around downloading and running selenium jars that I can't find elsewhere. I'm hoping the X11 dependency is eventually moved into a separate package.

**Comment by thomasjm** [comment]
For the record this library isn't officially released yet, but I'm glad you're checking it out :)

Funny you should mention this, I pushed code to master today and yesterday removing the X11 dependency, so this issue can actually be closed. I'll push it to Hackage soon.
